name: Docker

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  push:
    if: "!contains(github.event.head_commit.message, 'skip ci')"

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python:
          - "3.8"
          - "3.9"
          - "3.10"

    name: Tag Commit Python ${{ matrix.python }}

    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: renokigames/python-game-terrain:${{ matrix.python }}-${{ github.sha }}
          build-args: |
            PYTHON_VERSION=${{ matrix.python }}